# NOTE: IDE may show schema validation warnings for linters-settings, but this configuration is correct for golangci-lint v1.58.2
version: "1.58.2"
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
linters:
  enable:
    - gofumpt
    - govet
    - errcheck
    - staticcheck
    - revive
    - gosec
  disable:
    - unused
linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Print
      - fmt.Printf
      - fmt.Println
