# Minimal golangci-lint configuration with explicit control
version: "1.58.2"
run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - gofumpt
    - govet
    - staticcheck
    - revive
    - gosec
