# Minimal golangci-lint configuration to avoid compatibility issues
version: "1.58.2"
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
linters:
  enable:
    - gofumpt
    - govet
    - staticcheck
    - revive
    - gosec
  disable:
    - errcheck
    - goanalysis_metalinter
    - unused
