# Fixed golangci-lint configuration based on friend's feedback
version: "1.58.2"
linters:
  enable:
    - gofumpt
    - govet
    - staticcheck
    - revive
    - gosec
  disable:
    - unused
    - errcheck
    - goanalysis_metalinter
linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Print
      - fmt.Printf
      - fmt.Println
