name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-tools-v1.58.2-2
          restore-keys: |
            ${{ runner.os }}-go-tools-v1.58.2-
            ${{ runner.os }}-go-tools-

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Set up PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Format check
        run: make fmt-check

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: --timeout=5m

      - name: Test
        run: make test

      - name: API validate (optional)
        run: make api-validate
